### ISSUE TITLE
FILES.cfg file missing

### ISSUE THREAD

**Issue by mdedonno1337** [ungoogled-software/ungoogled-chromium-portablelinux#137]
Hi

The compilation seems not to work on my side, with the latest version of the repo.
This issue started with the update to chromium 99 I guess.

The error is at the end, while packaging the build:

```
root@a44ed64f374e:/repo# "$_root_dir/ungoogled-chromium/utils/filescfg.py" \
> -c "$_root_dir/build/src/chrome/tools/build/linux/FILES.cfg" \
> --build-outputs "$_root_dir/build/src/out/Default" \
> archive \
> -o "$_archive_output" \
> -i "$_root_dir/tar_includes/README"
Traceback (most recent call last):
  File "/repo/ungoogled-chromium/utils/filescfg.py", line 191, in <module>
    main()
  File "/repo/ungoogled-chromium/utils/filescfg.py", line 187, in main
    args.callback(args)
  File "/repo/ungoogled-chromium/utils/filescfg.py", line 124, in _archive_callback
    create_archive(
  File "/repo/ungoogled-chromium/utils/filescfg.py", line 94, in create_archive
    for relative_path in file_iter:
  File "/repo/ungoogled-chromium/utils/filescfg.py", line 29, in filescfg_generator
    with cfg_path.open() as cfg_file:
  File "/usr/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/repo/build/src/chrome/tools/build/linux/FILES.cfg'
```

Thanks

**Comment by mdedonno1337** [comment]
This isse seems to be the same as the one mentionned here @kramred in https://github.com/Eloston/ungoogled-chromium/pull/1850#issuecomment-1057811420 .

The fix in https://github.com/kramred/ungoogled-chromium-portablelinux/commit/a84a62f24b1884ac44c41e4aeeb398d1009fcca7 seems to work.

A PR done with the mentionned commit would be more than appriciated.

Thanks

**Comment by GersomR-afk** [comment]
Any fixes?
