### ISSUE TITLE
build.sh failure: TypeError: __init__() got an unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by emanruse** [ungoogled-software/ungoogled-chromium-portablelinux#41]
I am trying to build 80.0.3987.149-1.1 but build.sh fails and stops at:
```
+ /tmp/download/ungoogled-chromium-portablelinux/ungoogled-chromium/utils/patches.py apply /tmp/download/ungoogled-chromium-portablelinux/build/src /tmp/download/ungoogled-chromium-portablelinux/ungoogled-chromium/patches /tmp/download/ungoogled-chromium-portablelinux/patches
INFO: Applying patches from /tmp/download/ungoogled-chromium-portablelinux/ungoogled-chromium/patches
Traceback (most recent call last):
  File "/tmp/download/ungoogled-chromium-portablelinux/ungoogled-chromium/utils/patches.py", line 236, in <module>
    main()
  File "/tmp/download/ungoogled-chromium-portablelinux/ungoogled-chromium/utils/patches.py", line 232, in main
    args.callback(args)
  File "/tmp/download/ungoogled-chromium-portablelinux/ungoogled-chromium/utils/patches.py", line 189, in _apply_callback
    patch_bin_path=args.patch_bin)
  File "/tmp/download/ungoogled-chromium-portablelinux/ungoogled-chromium/utils/patches.py", line 111, in apply_patches
    patch_bin_path = find_and_check_patch(patch_bin_path=patch_bin_path)
  File "/tmp/download/ungoogled-chromium-portablelinux/ungoogled-chromium/utils/patches.py", line 67, in find_and_check_patch
    result = subprocess.run(cmd, capture_output=True, text=True)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by Eloston** [comment]
You seem to be running Python 3.6, but `capture_output` was introduced in 3.7, which is what Debian buster packages. Are you able to upgrade your Python to 3.7 or newer?

**Comment by emanruse** [comment]
> Are you able to upgrade your Python to 3.7 or newer?

My distro (openSUSE Leap 15.1) is up to date. Installing newer Python would either require adding unofficial repos (which is something that makes the system vulnerable + difficult to maintain long term) or building Python from source (which requires even more time and effort).

Is there any particular reason which makes Python 3.7 mandatory or can you make it compatible with 3.6 please?

*I was able to build 80.0.3987.132-1.1 without problems.

**Comment by Eloston** [comment]
I will add backwards compatibility with Python 3.6 then.

**Comment by Eloston** [comment]
921d053096e7595aa6ddabcc0af6e529a4f107c5

**Comment by emanruse** [comment]
Thank you.
