### ISSUE TITLE
Error building under debian

### ISSUE THREAD

**Issue by berkley4** [ungoogled-software/ungoogled-chromium-portablelinux#74]
Building under Debian unstable, I'm hitting an identical error to the one I mentioned in [debian issue #178](https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/178). I run into this building both 86.0.4240.111 and 86.0.4240.183.

Unless this issue is something specific to my setup (a chroot build), this would appear to be a debian issue since other distros seem able to build fine.

> [3498/43114] ACTION //third_party/blink/renderer/bindings:generate_bindings_all(//build/toolchain/linux/unbundle:default)
> .
> .
> python ../../third_party/blink/renderer/bindings/scripts/generate_bindings.py --web_idl_database gen/third_party/blink/renderer/bindings/web_idl_database.pickle --root_src_dir ../../ --root_gen_dir gen --output_core_reldir third_party/blink/renderer/bindings/core/v8/ --output_modules_reldir third_party/blink/renderer/bindings/modules/v8/ enumeration interface
> Traceback (most recent call last):
>   File "../../third_party/blink/renderer/bindings/scripts/generate_bindings.py", line 100, in <module>
>     main()
>   File "../../third_party/blink/renderer/bindings/scripts/generate_bindings.py", line 77, in main
>     task_queue = bind_gen.TaskQueue()
>   File "/home/berkley4/ungoogled-chromium-portablelinux/build/src/third_party/blink/renderer/bindings/scripts/bind_gen/task_queue.py", line 19, in __init__
>     package_initializer().init)
>   File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
>     return Pool(processes, initializer, initargs, maxtasksperchild)
>   File "/usr/lib/python2.7/multiprocessing/pool.py", line 140, in __init__
>     self._setup_queues()
>   File "/usr/lib/python2.7/multiprocessing/pool.py", line 236, in _setup_queues
>     self._inqueue = SimpleQueue()
>   File "/usr/lib/python2.7/multiprocessing/queues.py", line 352, in __init__
>     self._rlock = Lock()
>   File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
>     SemLock.__init__(self, SEMAPHORE, 1, 1)
>   File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
>     sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
> OSError: [Errno 13] Permission denied

**Comment by berkley4** [comment]
Closing this. I've managed to compile loads of times before (the debian version), but somehow my chroot's /dev/shm didn't have the required 1777 permissions.
