### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by alexmat** [ungoogled-software/ungoogled-chromium-portablelinux#99]
Not sure how to fix this. I was able to build version 87 on the same box with no issues.

```
[4505/48832] ACTION //third_party/devtools-frontend/src/front_end:html_entrypoints-generation(//build/toolchain/linux/unbundle:default)
FAILED: gen/third_party/devtools-frontend/src/front_end/devtools_app.html gen/third_party/devtools-frontend/src/front_end/inspector.html gen/third_party/devtools-frontend/src/front_end/js_app.html gen/third_party/devtools-frontend/src/front_end/ndb_app.html gen/third_party/devtools-frontend/src/front_end/node_app.html gen/third_party/devtools-frontend/src/front_end/toolbox.html gen/third_party/devtools-frontend/src/front_end/worker_app.html 
python ../../third_party/node/node.py ../../third_party/devtools-frontend/src/scripts/build/generate_html_entrypoint.js --template ../../third_party/devtools-frontend/src/front_end/entrypoint_template.html --out-directory gen/third_party/devtools-frontend/src/front_end
Traceback (most recent call last):
  File "../../third_party/node/node.py", line 44, in <module>
    RunNode(sys.argv[1:])
  File "../../third_party/node/node.py", line 24, in RunNode
    cmd, cwd=os.getcwd(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by zjlx** [comment]
I had the same error.version 90.0.4430.93-1.1,  Ubuntu18, nodejs 14 
I try to edit build.sh, delete the line 11,16,17. And edit file `ungoogled-chromium-portablelinux\build\src\third_party\node\node.py`
change 
```python
def GetBinaryPath():
  return os_path.join(os_path.dirname(__file__), *{
    'Darwin': ('mac', 'node-darwin-x64', 'bin', 'node'),
    'Linux': ('linux', 'node-linux-x64', 'bin', 'node'),
    'Windows': ('win', 'node.exe'),
  }[platform.system()])
```
to
```python
def GetBinaryPath():
  return 'node'
```
then run ./build.sh. the above error is disappeared.But appear a new bug.
```shell
../../base/check.h:88:3: error: 'nomerge' attribute cannot be applied to a declaration
  NOMERGE ~CheckError();
  ^       ~
../../base/compiler_specific.h:337:19: note: expanded from macro 'NOMERGE'
#define NOMERGE [[clang::nomerge]]
                  ^
1 error generated.
```
I also don't known how to fix it.
Hope help to you.

**Comment by zjlx** [comment]
Or change to version 86's GetBinaryPath()
```python
def GetBinaryPath():
  return subprocess.check_output(["which", "node"]).strip()
#  return os_path.join(os_path.dirname(__file__), *{
#    'Darwin': ('mac', 'node-darwin-x64', 'bin', 'node'),
#    'Linux': ('linux', 'node-linux-x64', 'bin', 'node'),
#    'Windows': ('win', 'node.exe'),
#  }[platform.system()])
```

**Comment by mdedonno1337** [comment]
This seems to be patched in the patches/debian/system/node2.patch file, or am I missing something ?

**Comment by zjlx** [comment]
I try version 90.0.4430.212-1.1 build.
It has the following error:
```shell
../../media/gpu/vaapi/vaapi_wrapper.cc:405:37: error: use of undeclared identifier 'VAProfileAV1Profile0'; did you mean 'VAProfileVP9Profile0'?
          {AV1PROFILE_PROFILE_MAIN, VAProfileAV1Profile0},
                                    ^~~~~~~~~~~~~~~~~~~~
                                    VAProfileVP9Profile0
/usr/include/va/va.h:373:5: note: 'VAProfileVP9Profile0' declared here
    VAProfileVP9Profile0                = 19,
    ^
../../media/gpu/vaapi/vaapi_wrapper.cc:442:26: error: use of undeclared identifier 'VAProfileAV1Profile0'; did you mean 'VAProfileVP9Profile0'?
    return va_profile == VAProfileAV1Profile0 &&
                         ^~~~~~~~~~~~~~~~~~~~
                         VAProfileVP9Profile0
/usr/include/va/va.h:373:5: note: 'VAProfileVP9Profile0' declared here
    VAProfileVP9Profile0                = 19,
    ^
../../media/gpu/vaapi/vaapi_wrapper.cc:1179:24: error: use of undeclared identifier 'VA_RT_FORMAT_YUV420_10'; did you mean 'PIXEL_FORMAT_YUV420P10'?
    if (attrib.value & VA_RT_FORMAT_YUV420_10)
                       ^~~~~~~~~~~~~~~~~~~~~~
                       PIXEL_FORMAT_YUV420P10
../../media/base/video_types.h:56:3: note: 'PIXEL_FORMAT_YUV420P10' declared here
  PIXEL_FORMAT_YUV420P10 = 17,
  ^
../../media/gpu/vaapi/vaapi_wrapper.cc:1501:10: error: use of undeclared identifier 'VA_RT_FORMAT_YUV420_10'; did you mean 'PIXEL_FORMAT_YUV420P10'?
    case VA_RT_FORMAT_YUV420_10:
         ^~~~~~~~~~~~~~~~~~~~~~
         PIXEL_FORMAT_YUV420P10
../../media/base/video_types.h:56:3: note: 'PIXEL_FORMAT_YUV420P10' declared here
  PIXEL_FORMAT_YUV420P10 = 17,
  ^
../../media/gpu/vaapi/vaapi_wrapper.cc:1588:29: error: use of undeclared identifier 'VA_FOURCC_Y216'
        preferred_fourcc == VA_FOURCC_Y216 ||
                            ^
../../media/gpu/vaapi/vaapi_wrapper.cc:1589:29: error: use of undeclared identifier 'VA_FOURCC_Y416'
        preferred_fourcc == VA_FOURCC_Y416 ||
                            ^
6 errors generated.
```

**Comment by mdedonno1337** [comment]
Still with your ubuntu 18 ?
I suspect a too old version of clang.
What is exactly your compilation environment ?
Can you try the build with docker ?

**Comment by alexmat** [comment]
The build works for me with 90.0.4430.212 and runs very well.

One small issue is nodejs is expected at /usr/bin/nodejs, but my distro uses /usr/bin/node. I simply added a symlink to node vi:

```bash
ln -s /usr/bin/node /usr/bin/nodejs
```

Other than that I had no isssues. Cheers!

**Comment by zjlx** [comment]
> Still with your ubuntu 18 ?
> I suspect a too old version of clang.
> What is exactly your compilation environment ?
> Can you try the build with docker ?

ubuntu18 clang11 llvm11
```shell
FAILED: obj/media/gpu/vaapi/common/vaapi_wrapper.o
clang++ -MMD -MF obj/media/gpu/vaapi/common/vaapi_wrapper.o.d -DMEDIA_GPU_IMPLEMENTATION -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DUSE_X11=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-13-init-1559-g01b87444-3\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=8fa87946779682841e21e2da977eccfb6cb3bded -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DWEBP_EXTERN=extern -DVK_USE_PLATFORM_XCB_KHR -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -Dtypeof\(x\)=__typeof__\(x\) -DSK_FAVOR_WUFFS_V_0_3_OVER_V_0_2 -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_WUFFS_LIBRARY -DSK_VULKAN_HEADER=\"../../skia/config/SkVulkanConfig.h\" -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DVK_USE_PLATFORM_XCB_KHR -DCRASHPAD_ZLIB_SOURCE_EXTERNAL -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DLEVELDB_PLATFORM_CHROMIUM=1 -DLEVELDB_PLATFORM_CHROMIUM=1 -DLIBGAV1_MAX_BITDEPTH=10 -DLIBGAV1_THREADPOOL_USE_STD_MUTEX -DLIBGAV1_ENABLE_LOGGING=0 -DLIBGAV1_PUBLIC= -DVK_NO_PROTOTYPES -DUSE_VULKAN_XCB -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../third_party/khronos -I../../gpu -I../../third_party/libwebp/src -I../../third_party/vulkan-deps/vulkan-headers/src/include -I../../third_party/libyuv/include -Igen/third_party/dawn/src/include -I../../third_party/dawn/src/include -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/libdrm/src -I../../third_party/libdrm/src/include -I../../third_party/libdrm/src/include/drm -I../../third_party/skia -I../../third_party/wuffs/src/release/c -I../../third_party/vulkan/include -I../../third_party/vulkan-deps/vulkan-headers/src/include -I../../third_party/crashpad/crashpad -I../../third_party/crashpad/crashpad/compat/linux -I../../third_party/crashpad/crashpad/compat/non_win -I../../third_party/zlib -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/ced/src -I../../third_party/protobuf/src -I../../third_party/libwebm/source -I../../third_party/mesa_headers -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/libgav1/src -I../../third_party/libgav1/src/src -fno-delete-null-pointer-checks -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -flto=thin -fsplit-lto-unit -fwhole-program-vtables -fcomplete-member-pointers -m64 -march=x86-64 -msse3 -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-max-tokens -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fsanitize=cfi-vcall -fsanitize-blacklist=../../tools/cfi/ignores.txt -fsanitize=cfi-icall -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DPROTOBUF_ALLOW_DEPRECATED=1 -Wno-\#pragma-messages -DMAJOR_IN_SYSMACROS=1 -Wno-enum-conversion -Wno-unused-result -Wno-shorten-64-to-32 -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -resource-dir=/usr/lib/llvm-11/lib/clang/11.1.0 -resource-dir=/usr/lib/llvm-11/lib/clang/11.1.0 -c ../../media/gpu/vaapi/vaapi_wrapper.cc -o obj/media/gpu/vaapi/common/vaapi_wrapper.o
../../media/gpu/vaapi/vaapi_wrapper.cc:405:37: error: use of undeclared identifier 'VAProfileAV1Profile0'; did you mean 'VAProfileVP9Profile0'?
          {AV1PROFILE_PROFILE_MAIN, VAProfileAV1Profile0},
                                    ^~~~~~~~~~~~~~~~~~~~
                                    VAProfileVP9Profile0
/usr/include/va/va.h:373:5: note: 'VAProfileVP9Profile0' declared here
    VAProfileVP9Profile0                = 19,
    ^
../../media/gpu/vaapi/vaapi_wrapper.cc:442:26: error: use of undeclared identifier 'VAProfileAV1Profile0'; did you mean 'VAProfileVP9Profile0'?
    return va_profile == VAProfileAV1Profile0 &&
                         ^~~~~~~~~~~~~~~~~~~~
                         VAProfileVP9Profile0
/usr/include/va/va.h:373:5: note: 'VAProfileVP9Profile0' declared here
    VAProfileVP9Profile0                = 19,
    ^
../../media/gpu/vaapi/vaapi_wrapper.cc:1179:24: error: use of undeclared identifier 'VA_RT_FORMAT_YUV420_10'; did you mean 'PIXEL_FORMAT_YUV420P10'?
    if (attrib.value & VA_RT_FORMAT_YUV420_10)
                       ^~~~~~~~~~~~~~~~~~~~~~
                       PIXEL_FORMAT_YUV420P10
../../media/base/video_types.h:56:3: note: 'PIXEL_FORMAT_YUV420P10' declared here
  PIXEL_FORMAT_YUV420P10 = 17,
  ^
../../media/gpu/vaapi/vaapi_wrapper.cc:1501:10: error: use of undeclared identifier 'VA_RT_FORMAT_YUV420_10'; did you mean 'PIXEL_FORMAT_YUV420P10'?
    case VA_RT_FORMAT_YUV420_10:
         ^~~~~~~~~~~~~~~~~~~~~~
         PIXEL_FORMAT_YUV420P10
../../media/base/video_types.h:56:3: note: 'PIXEL_FORMAT_YUV420P10' declared here
  PIXEL_FORMAT_YUV420P10 = 17,
  ^
../../media/gpu/vaapi/vaapi_wrapper.cc:1588:29: error: use of undeclared identifier 'VA_FOURCC_Y216'
        preferred_fourcc == VA_FOURCC_Y216 ||
                            ^
../../media/gpu/vaapi/vaapi_wrapper.cc:1589:29: error: use of undeclared identifier 'VA_FOURCC_Y416'
        preferred_fourcc == VA_FOURCC_Y416 ||
                            ^
6 errors generated.
[23683/48832] CXX obj/components/autofill/content/common/m...om/mojom_shared_cpp_sources/autofill_driver.mojom-shared.o
ninja: build stopped: subcommand failed.
```
